features_list = ["ADJ",
                 "ADV",
                 "NOUN",
                 "PROPN",
                 "VERB",
                 "ADP",
                 "AUX",
                 "DET",
                 "PRON",
                 "PronType=Art",
                 "PronType=Dem",
                 "PronType=Emp",
                 "PronType=Exc",
                 "PronType=Ind",
                 "PronType=Int",
                 "PronType=Neg",
                 "PronType=Prs",
                 "PronType=Rcp",
                 "PronType=Rel",
                 "PronType=Tot",
                 "Gender=Com",
                 "Gender=Fem",
                 "Gender=Masc",
                 "Gender=Neut",
                 "Number=Coll",
                 "Number=Count",
                 "Number=Dual",
                 "Number=Grpa",
                 "Number=Grpl",
                 "Number=Inv",
                 "Number=Pauc",
                 "Number=Plur",
                 "Number=Ptan",
                 "Number=Sing",
                 "Number=Tri",
                 "Case=Abs",
                 "Case=Acc",
                 "Case=Erg",
                 "Case=Nom",
                 "Case=Abe",
                 "Case=Ben",
                 "Case=Cau",
                 "Case=Cmp",
                 "Case=Cns",
                 "Case=Abl",
                 "Case=Add",
                 "Case=Ade",
                 "Case=All",
                 "Case=Del",
                 "Case=Com",
                 "Case=Dat",
                 "Case=Dis",
                 "Case=Equ",
                 "Case=Ela",
                 "Case=Ess",
                 "Case=Ill",
                 "Case=Ine",
                 "Case=Gen",
                 "Case=Ins",
                 "Case=Par",
                 "Case=Tem",
                 "Case=Lat",
                 "Case=Loc",
                 "Case=Per",
                 "Case=Sbe",
                 "Case=Tra",
                 "Case=Voc",
                 "Case=Sbl",
                 "Case=Spl",
                 "Case=Sub",
                 "Case=Sup",
                 "Case=Ter",
                 "Definite=Com",
                 "Definite=Cons",
                 "Definite=Def",
                 "Definite=Ind",
                 "Definite=Spec",
                 "Gender[psor]=Fem",
                 "Gender[psor]=Masc",
                 "Gender[psor]=Neut",
                 "Number[psor]=Plur",
                 "Number[psor]=Sing",
                 "Mood=Adm",
                 "Mood=Cnd",
                 "Mood=Des",
                 "Mood=Imp",
                 "Mood=Ind",
                 "Mood=Int",
                 "Mood=Irr",
                 "Mood=Jus",
                 "Mood=Nec",
                 "Mood=Opt",
                 "Mood=Pot",
                 "Mood=Prp",
                 "Mood=Qot",
                 "Mood=Sub",
                 "Tense=Fut",
                 "Tense=Imp",
                 "Tense=Past",
                 "Tense=Pqp",
                 "Tense=Pres",
                 "Aspect=Hab",
                 "Aspect=Imp",
                 "Aspect=Iter",
                 "Aspect=Perf",
                 "Aspect=Prog",
                 "Aspect=Prosp",
                 "Person=0",
                 "Person=1",
                 "Person=2",
                 "Person=3",
                 "Person=4",
                 "Animacy=Anim",
                 "Animacy=Hum",
                 "Animacy=Inan",
                 "Animacy=Nhum",
                 "SubGender=Masc1",
                 "SubGender=Masc2",
                 "SubGender=Masc3",
                 "PartType=Emp",
                 "PartType=Inf",
                 "PartType=Int",
                 "PartType=Mod",
                 "PartType=Neg",
                 "PartType=Vbp"]


def get_ud_features_dict():
    features_dict = {}
    idx = 0

    for feat in features_list:
        features_dict[feat] = idx
        idx += 1

    assert len(features_list) == len(features_dict)

    return features_dict


def get_ud_features_length():
    return len(get_ud_features_dict())